# Résumé {-}

Cette thèse est un travail de microéconométrie appliquée à l'économie de l'éducation qui s'intéresse à certains déterminants des performances scolaires et universitaires à La Réunion. Par rapport à la population de la France métropolitaine, celle de La Réunion est marquée par un contexte plus défavorable à l'accumulation de capital humain. Dans le premier chapitre, nous nous intéressons au lien causal entre l'âge au moment des examens et les performances scolaires. Nous trouvons que ce lien est positif et important et s'atténue au fil du temps. Nous mettons en plus en évidence qu'être plus jeune dans la classe implique de meilleures performances scolaires. Dans le deuxième chapitre, nous étudions les effets de pairs en éducation. Plus précisément, nous examinons l'effet du niveau scolaire et des comportements des camarades de classe en fin de collège sur la performance en fin de collège. Il en ressort essentiellement que les élèves les plus faibles scolairement ne bénéficient pas des effets de pairs alors que les autres d'élèves, bénéficient quant à eux de la présence des pairs les plus forts. Les effets positifs et importants du comportement des pairs sur les performances que nous trouvons en plus suggèrent qu'il peut être intéressant de proposer des interventions uniquement à une partie des élèves de la classe pour en faire bénéficier le reste, particulièrement en mathématiques. Le dernier chapitre s'intéresse à l'efficacité d'une plateforme numérique en ligne visant à maintenir le contact avec les mathématiques entre la fin du lycée et le début des études universitaires pour des étudiants néo-bacheliers en première année d'université. Nous constatons que la plateforme a été très peu utilisée par les étudiants et qu'elle n'a eu aucun impact sur les performances aux évaluations de mathématiques en fin de semestre. Toutefois, des effets sur le comportement des plus motivés nous suggèrent que de meilleures configurations de proposition de la plateforme, notamment une durée plus longue de mise à disposition aux étudiants, pourraient générer des effets positifs.  

**Mots-clés : ** déterminants des performances scolaires et universitaires, effets de l'âge, effets de pairs, interventions en mathématiques, notes, variables instrumentales.