# Abstract {-}

This thesis is a work on microeconometrics applied to economics of education that analyses some determinants of academic performances in Reunion Island. Compared to the population of metropolitan France, the population of Reunion Island suffers from a context that may hinders human capital accumulation. In the first chapter, we analyse the causal effect of age at test on academic performances in primary and secondary education. We find a strong and significant positive effect at the end of primary school that fades out over time. We additionally show that being younger relatively to classmates boost test scores. In the second chapter, we study peer effects in education. To be more precise, for pupils at the end of lower secondary school, we measure the effect of peers' (defined as classmates) past academic performances and peers' contemporary academic behaviours on pupil's academic performances. We find that the weakest pupils cannot benefit from any peer effect at all. However, the strongest peers have a positive effect on other pupils. The positive and strong effects of peers' academic behaviours that we additionaly figure out suggest that it may be interesting to implement interventions to a fraction of students in the classroom, expecting positive spillovers to their classmates, especially in mathematics. The last chapter focuses on the impact of an online platform that seeks to keep graduate students in touch with mathematics between the end of secondary school and the beginning of university, on first-year university mathematics performances. We observe that the platform was barely used and its use did not impact mathematics skills of students. However, we strongly suspect that the intervention influenced behaviours of the most motivated students in mathematics, in a way suggesting that better implementation parameters of the platform (a longer duration of use, for instance) could result in positive effects. 

**Keywords: ** determinants of academic performances, effects of age, peer effects, interventions in mathematics, test scores, instrumental variables.