---
output: html_document
editor_options: 
  chunk_output_type: console
---

Cette thèse s'intéresse à des déterminants microéconomiques des performances académiques au sein des trois niveaux d'éducation obligatoire (primaire, secondaire et supérieur) du système français, sur le territoire réunionnais.

<!-- ## L'importance de s'intéresser aux déterminants du niveau de capital humain {-} -->

\quad Le capital humain désigne l'ensemble des compétences et connaissances productives d'un individu sur le marché du travail^[@KUC:11]. Le lien théorique entre le niveau de capital humain et la croissance économique d'un pays a été surtout popularisé par Gary Becker [@BEC:09, par exemple]. Le stock de capital humain d'un individu est déterminé par l'éducation formelle ou par d'autres facteurs comme les caractéristiques familiales ou celles de ses camarades, au sens large. Puisqu'il s'agit d'une information facile d'accès, la durée de scolarité est le proxy du niveau de capital humain le plus utilisé dans les premières périodes des études empiriques [@PSA:PAT:18]. Le résultat empirique global est que la durée de scolarité affecte positivement le produit intérieur brut (PIB) [@SIA:REE:03]. Mesurer le niveau de capital humain par la durée de scolarité pose cependant différents problèmes. Notamment, cette mesure ne donne aucune information sur la qualité de la scolarité. Dans les pays où la qualité de la scolarité est insuffisante, il se pourrait que les compétences d'un adulte, par exemple, n'ait été déterminé que par des facteurs autres que l'éducation formelle elle-même<!-- Et la variable omise ? Et les caractéristiques de la famille ?-->. Les données sur les évaluations cognitives internationales, disponibles plus tard, constituent une meilleure mesure du niveau de capital humain. Avec en plus le développement des méthodes d'estimation de lien de causalité, une branche récente de la littérature confirme empiriquement, le niveau de capital humain d'un pays (mesuré par les résultats d'évaluations internationales) a un effet causal positif et significatif sur sa croissance [@HAN:WOE:15 ; @HAN:WOE:20]. Un résultat supplémentaire est que cet effet est d'autant plus fort que le contexte institutionnel du pays est de qualité [@HAN:WOE:20, pp. 178], hormis l'effet direct de la qualité institutionnelle sur la croissance. Ce second résultat est robuste à différentes mesures de la qualité institutionnelle^[Comme l'ouverture au commerce international [@TAH:eal:14] ou l'allocation des compétences [@MUR:eal:91]] qui est difficilement objective. 

Investir sur son capital humain est également intéressant pour l'individu puisqu'il est globalement lié à un meilleur salaire [@CAR:01 ; @HEC:eal:06 ; @PSA:PAT:18] et un meilleur état de santé [@MEA:eal:08 ou @WAL:20, pp. 78, par exemple]. Cet investissement est également connu pour ses externalités positives sur la société telles que la baisse de la criminalité [@LOC:04 ; @LOC:20], l'amélioration de certains comportements civiques [@DEE:20]<!--Les effets de pairs à introduire ici.-->. 

Puisqu'il est impossible de contrôler explicitement le niveau de capital humain, il est naturel de s'interroger sur les déterminants de celui-ci au niveau macroéconomique ou microéconomique. Parmi ces déterminants, il est possible de distinguer ceux directement liés à l'éducation formelle (sa quantité et sa qualité) de ceux qui ne le sont pas [@BRI:eal:79 ; @BRI:VIG:17]. Les premiers concernent par exemple les ressources matérielles, financières ou humaines de l'établissement scolaire. Les seconds correspondent typiquement aux caractéristiques socio-démographiques telles que l'environnement familial et culturel, l'âge ou le sexe des individus ou de leurs camarades^[Le terme camarade peut regroupe plusieurs notions. Il peut désigner les voisins de quartier ou les camarades de classe, entre autres.]. Une autre classification de ces facteurs est le degré avec lequel ils peuvent être influencés par les politiques publiques. Clairement, il est difficile, voire impossible pour les décideurs publics d'agir sur les caractéristiques de naissance (date de naissance, caractéristiques familiales à la naissance, sexe, potentiel intellectuel, etc.) alors qu'il est tout à fait envisageable d'établir des règles inhérentes au système éducatif telles que l'âge de la scolarisation obligatoire, la taille maximale des classes, l'affectation des enseignants et élèves dans les classes, entre autres. Ces deux classifications ne sont pas mutuellement exclusives.
  
\quad Cela justifie dans une certaine mesure les efforts effectuées par les pays du monde pour l'éducation et plus particulièrement les pays développés<!--NB : si l'école sert à apprendre-->. Les pays de l'OCDE consacrent en moyenne 6.1\% de leur PIB en 1997 [@OCDR:00, pp. 49], 5.7\% en 2007 [@OCDR:10, pp. 218] et 4.9\% en 2017 [@OCDR:20, pp. 290]^[Cette diminution vient du fait que le montant des dépenses pour l'éducation a globalement augmenté mais pas autant que le PIB [@OCDR:20, pp. 290].]. 

Particulièrement, la France, avec un PIB par habitant dans la moyenne des pays de l'OCDE [@RAG:08, pp. 46, par exemple], se situe au-dessus de la moyenne en termes de part de PIB consacré à l'éducation [@RAG:08 ; @BRI:RUD:11]. Cette comparaison internationale se maintient à travers le temps et même en considérant la dépense annuelle par élève/étudiant comme indicateur de l'effort national en faveur de l'éducation [@DAL:eal:11].  


Aussi, depuis les années 80, la part des dépenses intérieures d'éducation dans le produit intérieur brut français varie aux alentours de 7\% (Figure \@ref(fig:diefrance2019)). Selon un rapport de la cour des comptes sur le système éducatif dans les outre-mer [@COU:20, pp.20], les dépenses pour les outre-mer sont supérieures aux moyennes métropolitaines. Particulièrement, environ 40\% des dépenses éducatives de 2018 concernent La Réunion. 

```{r, "diefrance2019", fig.cap = "Évolution de la dépense intérieure d'éducation française et de sa part dans le produit intérieur brut"}
die_france2019 <- image_read(here("images", "die_france2019.png")) %>% rasterGrob(interpolate = TRUE)
qplot() + annotation_custom(die_france2019
                            # , xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf
                            ) + 
  labs(caption = "Source : DEPP (2021), pp. 332.") + 
  theme(panel.background = element_rect(fill = "white")) + 
  mytheme %>% 
  (function (m) {
    m$plot.caption <- element_text(size = m$plot.caption$size,
                                   hjust = 0)
    m
  })
```

Malgré ces efforts, les jeunes élèves de la France se situe généralement en dessous de la moyenne de l'OCDE en termes de résultats aux évaluations internationales portant sur diverses compétences. Par exemple, pour les performances en compréhension de l'écrit issues l'évaluation PIRLS 2016 (*Progress in International Reading Literacy*), les élèves du CM1 de la France obtiennent un score nettement inférieur à ceux des pays de l'OCDE [@COL:LEC:17]. Il en est de même en mathématiques et en sciences pour les élèves du CM1 ayant participé aux éditions 2019 des évaluations du TIMSS (*Trends in Mathematics and Science Study*) [@COL:LEC:20]. Cela rentre en cohérence avec une hypothèse récente de la recherche selon laquelle la quantité des moyens alloués pour l'éducation n'implique pas de bonnes performances et qu'il est plus raisonnable de penser que c'est la manière d'utiliser ces moyens qui importe [@HAN:20, pp. 168].  
De plus, la France est connue pour présenter une association plus forte par rapport à la plupart des autres pays de l'OCDE entre le niveau social des parents et les performances scolaires des élèves [@CHA:eal:19 ; @BER:eal:19 ; @LEC:PAC:19 ; @LEM:eal:17, pp. 1]<!--Attention : il y a des pays dans lequel l'association entre la csp et les performances scolaires sont plus fortes : voir Tableau 2.8 de hanushek_woessmann2011.-->. Cette association a en plus augmenté depuis ces 20 dernières années alors qu'elle est en moyenne restée stable chez les pays de l'OCDE [@LEM:eal:17, pp. 5]. 
  
En plus de cette première forme d'inégalité, la France se caractérise par de fortes inégalités territoriales, surtout entre la France métropolitaine et les DROM (Départements et Régions d'Outre-Mer). @BOU:eal:16 [pp. 19] mettent par exemple en évidence, sur des données de recensement de 2011, des indicateurs de scolarisation des 15-24 ans unanimement plus mauvais dans l'ensemble des DROM, hors Mayotte. Cette situation plus difficile est également observée sur des indicateurs socio-économiques, puisque la part des jeunes de moins de 17 ans d'origine sociale défavorisée est supérieure de 10 points de pourcentage dans les DROM par rapport à la France métropolitaine<!--Taux de chômage ? (dares2018, lHorty2014), les structures familiales ? (marie_breton2015), le revenu ? (michel_eal2010)-->. 
  
Cette situation moyenne particulière des DROM est généralement retrouvée à travers chacune d'entre eux mais n'est pas due à une seule avec une situation extrême. Parmi les DROM, La Réunion est particulièrement caractérisé par la grande taille et le jeune âge de sa population [@COU:20]. Cette caractéristique mérite une attention particulière dans la mesure où les nombreux jeunes présentent de grandes difficultés scolaires [@SIM:15] pouvant être la cause du décrochage scolaire qui y persiste [@IDE:20]. Aussi, à La Réunion, la langue maternelle et la langue la plus souvent parlée est majoritairement le créole réunionnais alors que la langue d'enseignement est le français [@VAL:21, pp. 122], ce qui pourrait poser un problème d'apprentissage aux élèves réunionnais [@DAL:21, pp. 12]<!--Qualité de cette citation à revoir-->. 
  