Dans cette thèse, nous nous proposons d'estimer, pour La Réunion, trois spécifications de la fonction de production d'éducation à travers différents niveaux clés du système éducatif français, que cela concerne l'éducation obligatoire ou non. Se focaliser sur La Réunion est intéressant au vu des fortes différences en défaveur de  l'île par rapport à la France métropolitaine sur de multiples dimensions (géographique, économique, social et culturel), notamment sur l'éducation. 
   
Par exemple, à cause de la grande proportion d'élèves dont la langue maternelle n'est pas le français alors que ce dernier est la langue d'enseignement, des difficultés d'apprentissage peuvent toucher plus fortement les plus jeunes. Ceci peut constituer une problématique supplémentaire à celle de la règle unique d'entrée à l'école qui implique que des enfants avec des différences significatives d'âge reçoivent les mêmes enseignements alors qu'ils sont évalués uniformément. Les plus jeunes peuvent alors être fortement désavantagés uniquement à cause de leur âge, que cela soit à l'entrée à l'école, par rapport à leurs camarades de classe ou au moment des évaluations. Cette vision nous incite à étudier le lien entre l'âge des enfants et leurs résultats scolaires.  
  
Nous étudions d'abord ce lien en fin de l'école primaire. Ce niveau est crucial dans la mesure où à partir du collège, en fonction de leurs résultats en fin de primaire, les élèves peuvent être placés dans des classes assez différents en termes de ressources mobilisées, même si le programme et les évaluations sont uniformes. Nous regardons ensuite si les différences de résultats scolaires dues à des différences d'âge de même nature et de même ampleur sont plus grandes, plus petites ou ont disparu à la fin du collège. Dans la mesure où la vitesse de maturité diminue considérablement avec l'âge, les effets de l'âge sur les résultats scolaires devraient disparaître au fur et à mesure du temps. Si elles persistent et qu'il existe des différenciations de parcours scolaire en fonction des performances passées à une étape du système éducatif, alors les plus jeunes seront injustement d'une cohorte d'élèves seront surreprésentés dans les parcours offrant relativement moins d'opportunités. 
  
Avec la mobilisation des méthodes appropriées permettant de s'affranchir des biais pouvant le plus induire en erreur sur les effets de l'âge, nous trouvons que dans une cohorte de réunionnais, être plus âgé au moment des examens implique en soi un fort désavantage en termes de résultats scolaires en fin de primaire. Nous avons des éléments suggérant que le phénomène à l'origine de cette relation causale est le manque de préparation des plus jeunes par rapport à leurs camarades plus âgés au moment de l'entrée dans l'éducation formelle. Ceci étant dit, même étant moins préparé, être plus jeune dans la classe (et non dans la cohorte) se révèle être un avantage pour les élèves. Le système éducatif réunionnais a pu faire en sorte que les effets de l'âge, en somme, soient moins forts à la fin du collège mais restent significatifs. Cette somme d'effet se décompose d'un effet plus fort de l'âge aux examens (/d'entrée) par rapport à celui trouvé en primaire mais contrecarré par un effet plus important d'être parmi les plus jeunes de la classe. 
  
\quad Le système éducatif français, reflété à La Réunion, est caractérisé par un nombre plus faible de collèges (et donc de plus grande taille) par rapport au nombre d'écoles. Il est alors plus crucial de connaître s'il y a des manières d'attribuer les classes aux élèves plus efficaces que d'autres, notamment en termes de résultats scolaires. De plus, les élèves, plus grands par rapport au primaire ont plus de potentiel d'interactions avec leurs camarades ou leurs enseignants. La quasi-totalité des collèges réunionnais forment pratiquement et indirectement des classes de niveau, malgré le fait que cela soit interdit par le collège unique. Il est important de savoir dans quelles mesures elles sont légitimes ou non, outre via la justification de la facilité pédagogique<!--Mazenod2021 offre une petite littérature en page 95-->. Ces éléments nous ont amené au second chapitre de la thèse qui se repose sur les résultats aux examens nationaux en fin de collège pour étudier le lien entre ces derniers et les camarades de classe du collège. 
  
Nos méthodes permettent également de s'assurer que l'essentiel du lien trouvé est causal. Nos résultats suggèrent qu'il ne semble pas possible d'aider les plus faibles avec les seuls effets de pairs, de plus que ces élèves les plus faibles nuisent à leurs camarades de plus haut niveau, excepté les plus forts. Ces derniers semblent de leur côté faire bénéficier de leur présence pour leurs camarades plus faibles (sauf les plus faibles) et le bénéfice est maximal lorsque les élèves les plus forts se retrouvent entre eux. Nous fournissons des arguments appuyant que ces résultats reflètent au moins en partie un comportement adaptatif de l'enseignant en fonction de la composition de la classe en termes de niveau scolaire. 
Un second groupe de résultats du deuxième chapitre suggère que les comportements des camarades de classes vis-à-vis du français et des mathématiques eux-mêmes ont également des effets sur les résultats respectifs en ces matières, et cela au moins dès la fin du primaire. Le collège semble amplifier ces effets pour les mathématiques et les atténuer pour le français. Ces effets apparaissent les plus important dans les collèges en éducation prioritaire, c'est-à-dire considérés comme composé d'une part assez importante d'élèves d'origine défavorisés pour bénéficier de moyens supplémentaires par rapport aux autres établissements. Cela reflète probablement le fait que les élèves désavantagés sont plus dépendants du contexte scolaire pour leur apprentissage. 
    
\quad Les élèves de La Réunion, en plus d'être plus faibles en mathématiques par rapport à ceux de la métropole, subissent des effets relativement plus élevés en mathématiques au collège, d'après les deux chapitres précédents. Cela peut provoquer des inégalités à plus long terme via la différenciation des parcours à partir du lycée. Par exemple, les élèves plus faibles en mathématiques choisiront moins les filières scientifiques et cela en partie à cause de leur simple date de naissance et du manque de camarades plus forts dans leurs classes. À côté de cela subsiste un problème internationalement connu qu'est l'insuffisance du niveau en mathématiques des étudiants en général à l'entrée de l'université. Ces motivations nous amènent dans le dernier chapitre à s'intéresser aux néo-bacheliers de l'Université de La Réunion et à évaluer l'efficacité d'une intervention de révision des mathématiques pendant les vacances à l'aide d'une méthode permettant de s'affranchir du biais de sélection. Nous montrons dans ce chapitre que les élèves ont très peu reçu l'intervention en général, celle-ci a su modifier le comportement d'une petite partie d'étudiants motivés mais pas nécessairement forts *a priori* en mathématiques mais n'a modifié en rien leur niveau en mathématiques.
  
\quad En somme, les différentes spécifications et estimations de la fonction de production d'éducation proposées dans cette thèse semblent dire que pour La Réunion, une autre forme d'injustice autre que celle liée à l'origine sociale, liée à la seule date de naissance des élèves existe dès le primaire, probablement dès les premières années. Le collège ne réussit pas à résoudre dissiper cette forme d'injustice, en plus d'avoir une marge de progression sur l'allocation des élèves de différents niveaux scolaires à travers les classes. Vu les relations qui ressortent entre les comportements des collégiens, surtout en mathématiques, une simple intervention basée sur la continuité du contact avec les mathématiques entre la fin du lycée ne suffit pas, sur la quantité, sur la qualité ou sur le type-même. 
    
\quad Nos premiers résultats suggèrent que des politiques d'avancement de la date seuil pour entrer en primaire peuvent être intéressantes pour les élèves. Mais ce genre de mesure se décide au niveau national. Or, il n'est pas certain que ces conclusions soient valables pour toute la France vu les résultats que reportent @GRE:10^[Dans cette thèse, l'effet de l'âge apparaît plus fort chez les élèves privilégiés en fin de primaire tandis @GRE:10 obtient des effets plus forts chez les élèves désavantagés sur des résultats scolaires au tout début du collège.]. Considérant l'autonomie attribuée à l'académie de La Réunion, il serait plus pratique de sensibiliser tous les enseignants du primaire ainsi que les parents sur les effets de l'âge en soi. Pour commencer, il serait raisonnable de cibler ces sensibilisations prioritairement aux enseignants les moins qualifiés, les moins expérimentés et les plus jeunes ainsi que les parents les moins qualifiés et issus de catégories sociales défavorisées, entre autres. Ce sont les personnes qui ont le plus de chance de ne pas être conscients ou convaincus de l'ampleur des effets de l'âge sur les résultats scolaires à bas âge et les conséquences à plus long termes.  
  
Même s'ils ne prétendent pas impliquer des politiques d'allocations optimales des élèves réunionnais à travers les différentes classes de leur établissement, les résultats sur les effets de pairs plaident d'un côté pour répartir les plus forts équitablement dans les classes si l'objectif est spécifiquement d'augmenter la performance des moins forts. À cet objectif correspond un objectif concurrent qui est d'augmenter la performance moyenne de l'établissement. Dans ce cas, comme les effets de pairs trouvés pour La Réunion sont les plus élevés entre les élèves les plus forts eux-mêmes, il est dans l'intérêt des établissements de former de ne regrouper que les plus forts entre eux. Dans tous les cas, il semble intéressant de regrouper les plus faibles entre eux mais des compensations sont nécessaires puisque cette configuration entraîne fatalement une ségrégation sociale, entre autres<!--Citer étude anglais, mazenod2021-->. <!--Politiques sur les effets de pairs endogènes ? et le chapitre 3 ?-->  
  
L'évaluation de l'intervention de révision des mathématiques pour les étudiants en début de première année universitaire incite au mieux de modifier les paramètres de l'intervention ou de sa mise en œuvre pour que les concernés en bénéficient à plus forte dose. Nous suggérons modestement d'essayer dans les prochaines recherches une exposition plus longue des étudiants. Cela serait rentrerait d'ailleurs plus en accord avec l'objectif de l'intervention puisqu'avec un accès plus long, les étudiants peuvent bien rester plus en contact avec les mathématiques du lycée, leur permettant potentiellement de mieux suivre cours de mathématiques de l'université. 
  
\quad Comme tout travail de recherche, la présente thèse comporte ses limites mais ces dernières donnent l'occasion d'ouvrir de nouvelles perspectives pour La Réunion, un département d'outre-mer encore fertile pour la recherche, en tout cas en économie de l'éducation. Dans le premier chapitre, il aurait été intéressant de s'intéresser sur les effets de l'âge sur les parcours scolaires (redoublement, filière choisie, entrée aux études supérieures) et des mesures non cognitifs [@GIV:20] avec les mêmes méthodes et les mêmes spécifications. Cela aurait vraisemblablement permis de mieux comprendre les mécanismes pouvant certaines parties des résultats contraires à ceux de la littérature. Typiquement, une des raisons pour lesquelles les effets de l'âge restent visibles en fin de collège c'est que les plus jeunes, dû au désavantage de l'âge, perdent confiance en eux, développent des attitudes négatives vis-à-vis de l'école, etc., ce qui diminue significativement leur effort consenti aux études. Dans la même logique, les écarts de performance plus jeune peuvent augmenter la probabilité de redoubler, ce qui, à son tour, démotive les plus jeunes. Il reste également possible que même si les effets de l'âge ont diminué en fin de collège par rapport à la fin de primaire, les différentiations de parcours au début du lycée amplifient de nouveau les effets de l'âge.  
  
Dans le chapitre sur les effets de pairs, il aurait été sûrement intéressant d'estimer les mêmes modèles de forme réduite au primaire, ce dernier ne contenant pas les sections qui permettent la formation indirecte de classes de niveau comme au collège. Cela nécessite des données sur des résultats antérieures au CM2 (CP ou CE1). La difficulté de cet exercice est qu'une grande proportion d'écoles n'hébergent qu'une unique classe de CM2, ce qui empêche les estimations d'effets de pairs en forme réduite telles que dans le deuxième chapitre pour ces écoles. Pour la fin du collège, les mêmes types de limites liées à l'absence de mesures non cognitives sont également à mentionner puisqu'elles auraient grandement aidé à une meilleure compréhension des résultats. Nous aurions par exemple pu affirmer avec plus d'assurance dans quelles mesures c'est bien le comportement adaptatif des enseignants qui expliquent l'effet positif de la présence des élèves forts sur leurs semblables ou c'est l'esprit de compétition, par exemple. De la même manière, si nous pouvions observer par exemple que les plus faibles n'étaient pas démotivés par la présence de pairs plus forts, cela entrerait en forte cohérence avec l'absence d'effet négatif des pairs scolairement plus forts sur les élèves les plus faibles.  
Sur la base des effets de pairs estimés en forme réduite, des simulations sur différentes formes d'allocations des élèves de différents niveaux scolaires dans les différentes classes, leurs établissements étant fixés, auraient permis de fournir des recommandations encore plus précises. En outre, les ampleurs des effets de pairs endogènes ressortis de nos modèles sont trop grandes pour ne pas suspecter un problème méthodologique non détecté jusque-là. Cet éventuel problème ne modifiera cependant pas la qualité des effets de pairs endogènes trouvés (effets forts et surtout en mathématiques) vu que les mêmes faits stylisés sont reportés par les autres papiers qui font appel à la méthodologie d'estimation concernée [@BOU:eal:14 ; @IZA:DIC:20].  
  
En ce qui concerne le dernier chapitre de la thèse, la limitation aux étudiants intéressés au début de l'expérimentation est en soi une limite puisque nous avons montré qu'ils n'étaient pas représentatifs des néo-bacheliers en général. Une possibilité d'améliorer ce point est de commencer d'éventuelles expérimentations similaires futures par tous les inscrits aux deux filières et d'utiliser plutôt les mails étudiants pour ne pas avoir à demander le consentement des étudiants pour l'ouverture des comptes utilisateurs de la plateforme. La non-uniformité de la mesure des notes de mathématiques (des examens) pour tous les participants de l'expérimentation est une limite importante déjà discutée dans le corps du texte. Il n'est pas envisageable de faire des estimations séparées par filière puisque les échantillons seraient trop faibles, surtout pour des estimations par variables instrumentales. Le traitement très faible pose également problème pour la production de connaissances car nous ne saurions pas prédire si l'intervention aurait été plus efficace ou non si les participants auraient été plus allés sur la plateforme. Sans être péjoratif, le caractère jeune de la plateforme implique probablement qu'il est possible d'améliorer son attractivité et son contenu pour espérer maximiser son utilisation et obtenir des effets positifs visibles. La présence d'intéressés et de non intéressés par la plateforme est vraisemblablement une occasion d'étudier les effets de pairs à l'université<!--Please elaborate-->. Enfin, une autre intervention sur le français écrit est parallèlement concernée par l'expérimentation décrite dans le dernier chapitre de cette thèse mais nous n'avons pas pu récupérer les données statistiques correspondantes dans les temps. L'évaluation d'une telle intervention trouve tout son intérêt puisque le français écrit est une autre compétence de base qui sert vraisemblablement à la réussite des études universitaires [@BEL:eal:17]. Les effets potentiels de l'interaction entre les deux interventions auraient également fait un objet d'étude si cela avait été possible. 
  
\quad En somme, avant cette thèse, peu a été connu sur la fonction de production d'éducation à La Réunion. À l'issu de nos recherches, de modestes connaissances sont rajoutées à différents niveaux de l'éducation formelle et concernant plusieurs déterminants ainsi qu'une intervention. Ces connaissances confirment le caractère particulier du contexte réunionnais mais beaucoup restent à approfondir pour pouvoir proposer des politiques publiques plus précises et améliorer *in fine* l'efficacité du système éducatif français, au moins vis-à-vis des inégalités territoriales entre la France métropolitaine et les outre-mer. 

<!--autres y, mécanismes sous-jacents, autres interventions que les maths, -->


\newpage
  
## Bibliographie {-}
  
<div id="refs"></div>
